/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.

 */
package gui;

import java.io.DataOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
@author Rakshilkumar
 */
public class Fd extends javax.swing.JFrame {
 String amt="",ti="",pr="",age="";
    /**
     * Creates new form Fd
     */
 double p1,amo;
 int t1,a;
    Registration obj=null;
    public Fd()
    {
        
       initComponents();
      
    }
    public Fd(Registration obj) {
       this.obj=obj;
      
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t = new javax.swing.JTextField();
        p = new javax.swing.JTextField();
        exit = new javax.swing.JButton();
        am = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ag = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Enter principal amount :");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Enter time in months :");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Your Amount at Maturity :");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Rs. ");

        t.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tKeyTyped(evt);
            }
        });

        p.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pActionPerformed(evt);
            }
        });
        p.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pKeyTyped(evt);
            }
        });

        exit.setBackground(new java.awt.Color(0, 0, 0));
        exit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        am.setBackground(new java.awt.Color(0, 0, 0));
        am.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        am.setForeground(new java.awt.Color(255, 255, 255));
        am.setText("Calculate Amount");
        am.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("AGE : ");

        ag.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agActionPerformed(evt);
            }
        });
        ag.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                agKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                agKeyTyped(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ag, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(am)))
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(265, 265, 265))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ag, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(am))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(exit)
                .addGap(91, 91, 91))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void pKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pKeyTyped
         char c = evt.getKeyChar();
         if(Character.isLetter(c) && !evt.isAltDown()|| c=='\b')
         {
             evt.consume();
         }
            
    }//GEN-LAST:event_pKeyTyped

    private void pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pActionPerformed

    private void tKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tKeyTyped
        char c = evt.getKeyChar();
         if((Character.isDigit(c))|| c=='\b')
         {
             t.setEditable(true);
         }
         else
         {  JOptionPane.showMessageDialog(null,"Enter only integer");
             t.setText(null);
         
         }
    }//GEN-LAST:event_tKeyTyped
private int readNoofaccount() throws IOException {
        try
        {
            File fin = new File("E:\\An1\\"+"FD");
         
            int n = fin.listFiles().length;
          
            
            return n;
        }
        catch(FileNotFoundException e)
        {
            return 0;
        }
        catch(NullPointerException e)
        {
            return 0;
        }
    }
    private void amActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amActionPerformed
       //starting of code
         p1 = Double.parseDouble(p.getText());
        t1 = Integer.parseInt(t.getText());
        a=Integer.parseInt(ag.getText());
       double r=0.0;
        
       if(p1>1000000) 
       {
           JOptionPane.showMessageDialog(null,"Enter principal amount less than 1000000 ");
       }
       else{
       if(t1>48)
       {
           JOptionPane.showMessageDialog(null,"Invalid Credential");
             p.setText(null);
        t.setText(null);
        ag.setText("");
       
        //na.setText("");
        //male.setSelected(false);
     //   female.setSelected(false);
       }
       else
       {    String c = (obj.gender);
      
               
           if( c.equals("Male"))
           {
               if((Integer.parseInt(ag.getText()))>60)
               {
                   if(t1>0 && t1<=6)
                   {
                       r=6.20;
                   }
                   else if(t1>6 && t1<=12)
                   {
                       r=6.25;
                   }
                   else if(t1>12 && t1<=18)
                   {
                       r=6.50;
                   }
                   else if(t1>18 && t1<=24)
                   {
                       r=6.75;
                   }
                   else if(t1>24 && t1<=30)
                   {
                       r=6.80;
                   }
                   else if(t1>30 && t1<=36)
                   {
                       r=6.85;
                   }
                   else if(t1>36 && t1<=48)
                   {
                       r=6.87;
                   }
                   
               }
               else
               {
                   if(t1>0 && t1<=6)
                   {
                       r=5.05;
                   }
                   else if(t1>6 && t1<=12)
                   {
                       r= 5.10;
                   }
                   else if(t1>12 && t1<=18)
                   {
                       r=5.60;
                   }
                   else if(t1>18 && t1<=24)
                   {
                       r=5.75;
                   }
                   else if(t1>24 && t1<=30)
                   {
                       r=5.80;
                   }
                   else if(t1>30 && t1<=36)
                   {
                       r=5.85;
                   }
                   else if(t1>36 && t1<=48)
                   {
                       r=6.01;
                   }
               }
           }
           else {
               if(c.equals("Female"))
               {
                   if((Integer.parseInt(ag.getText()))>58)
                   {
                       if(t1>0 && t1<=6)
                       {
                           r=6.20;
                       }
                       else if(t1>6 && t1<=12)
                       {
                           r=6.25;
                       }
                       else if(t1>12 && t1<=18)
                       {
                           r=6.50;
                       }
                       else if(t1>18 && t1<=24)
                       {
                           r=6.75;
                       }
                       else if(t1>24 && t1<=30)
                       {
                           r=6.80;
                       }
                       else if(t1>30 && t1<=36)
                       {
                           r=6.85;
                       }
                       else if(t1>36 && t1<=48)
                       {
                           r=6.87;
                       }
                       
                   }
                   else
                   {
                       if(t1>0 && t1<=6)
                       {
                           r=5.05;
                       }
                       else if(t1>6 && t1<=12)
                       {
                           r= 5.10;
                       }
                       else if(t1>12 && t1<=18)
                       {
                           r=5.60;
                       }
                       else if(t1>18 && t1<=24)
                       {
                           r=5.75;
                       }
                       else if(t1>24 && t1<=30)
                       {
                           r=5.80;
                       }
                       else if(t1>30 && t1<=36)
                       {
                           r=5.85;
                       }
                       else if(t1>36 && t1<=48)
                       {
                           r=6.01;
                       }}
               }
           }
                      
          } 
       
     int t2= ((t1)/3);
     int t3= (t1-t2*3);
     
//     double am1 = p1*Math.pow((1+((r/4)/100)),t2);
double am1 = p1*Math.pow((1+((2.5/4)/100)),t2);
     if(t3>0)
     {
//          amo = am1*Math.pow((1+((r/12)/100)),t3);
         amo = am1*Math.pow((1+((2.5/12)/100)),t3);
     }
       else
     {
         amo=am1;
     }
    am.setText("Rs "+amo+"");}
      
      pr=p.getText();
      ti=t.getText();
      age=ag.getText();
      amt=am.getText();
      //?*//
    // new File("E:\\An1\\"+s).mkdir();
    int i=0;
     try {
         i = readNoofaccount();
     } catch (IOException ex) {
        ex.printStackTrace();
     }
    try{      
    FileOutputStream fout;
           fout = new FileOutputStream("E:\\An1\\FD\\"+("FD".substring(0,2))+" "+(i+1)+".txt");
           DataOutputStream re = new DataOutputStream(fout);
           //r.writeInt(1);
           re.write(("Username : "+(new Next(obj).t)).getBytes());
           re.write(System.getProperty( "line.separator" ).getBytes());
           re.write(("Password : "+(new Next(obj).y)).getBytes());
           re.write(System.getProperty( "line.separator" ).getBytes());
           re.write(("Name : "+obj.nam).getBytes());
           re.write(System.getProperty( "line.separator" ).getBytes());
           re.write(("Father's Name : "+obj.fat).getBytes());
           re.write(System.getProperty( "line.separator" ).getBytes());
           re.write(("Date of birth : "+obj.d).getBytes());
           re.write(System.getProperty( "line.separator" ).getBytes());
           
           re.write(("Date of Opening "+"FD Account : "+(new Next(obj)).dat).getBytes());
           re.write(System.getProperty( "line.separator" ).getBytes());
           re.write(("Gender : "+obj.gender).getBytes());
           re.write(System.getProperty( "line.separator" ).getBytes());
            re.write(("Addhar Card : "+(obj.adr)).getBytes());
             re.write(System.getProperty( "line.separator" ).getBytes());
             
               re.write(("Mobile No : "+obj.mo).getBytes());
               re.write(System.getProperty( "line.separator" ).getBytes());
               re.write(("Occupation : "+obj.jo).getBytes());
               re.write(System.getProperty( "line.separator" ).getBytes());
               re.write(("Address : "+obj.ac).getBytes());
               re.write(System.getProperty( "line.separator" ).getBytes());
               
               String msg="";
               msg="<html> YOUR ACCOUNT HAS BEEN SUCCESSFULL CREATED !!! <br>"+
                       "<br>"
                       + "PLEASE REMEMBER YOUR UNIQUE ACCOUNT ID GIVEN BELOW <br>"+"<br>"
                                + "YOUR ACCOUNT ID IS:  "+("FD".substring(0,2))+" "+(i+1)+ "</html>";
             JOptionPane op = new JOptionPane();
        op.setMessage(msg);
     
        op.setMessageType(JOptionPane.INFORMATION_MESSAGE);
        JDialog dialog = op.createDialog(null,"Important Note");
        dialog.setVisible(true);
               
               
//               String z=new Next(obj).t;
//               System.out.println(z);
              // System.out.println(new Next(obj).t);
               
      //iska socho 
              
            
                re.write(("Age of Person is : "+(age)).getBytes());
                re.write(System.getProperty( "line.separator" ).getBytes());
                re.write(("Principal amount deposited is : "+pr).getBytes());
                re.write(System.getProperty( "line.separator" ).getBytes());
                re.write(("Time period of FD : "+ti).getBytes());
                re.write(System.getProperty( "line.separator" ).getBytes());
                re.write(("Amount at maturity : "+amt).getBytes());
                re.write(System.getProperty( "line.separator" ).getBytes());
     
    }
    catch(IOException e)
    {
        
    }
     
    }//GEN-LAST:event_amActionPerformed
//end of code
    private void agActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agActionPerformed
       System.out.println(1);
    }//GEN-LAST:event_agActionPerformed

    private void agKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_agKeyTyped
       char c = evt.getKeyChar();
         if((Character.isDigit(c))|| c=='\b')
         {
             ag.setEditable(true);
         }
         else
         {  JOptionPane.showMessageDialog(null,"Enter only integer");
             ag.setText(null);
         
         }
    }//GEN-LAST:event_agKeyTyped

    private void agKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_agKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_agKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
ag.setText("");
p.setText("");
t.setText("");
am.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Registration obj = new Registration();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Fd(obj).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ag;
    private javax.swing.JButton am;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField p;
    private javax.swing.JTextField t;
    // End of variables declaration//GEN-END:variables
}
